/**
 * Created by Snippy Valson on 21/7/16.
 */
var stations=[
    {
        "name":"Alappuzha",
        "code":"ALLP"
    },
    {
        "name":"Aluva",
        "code":"AWY"
    },
    {
        "name":"Angamaly",
        "code":"AFK"
    },
    {
        "name":"Badagara",
        "code":"BDJ"
    },
    {
        "name":"Bekal Fort",
        "code":"BFR"
    },
    {
        "name":"Calicut",
        "code":"CLT"
    },
    {
        "name":"Cannanore",
        "code":"CAN"
    },
    {
        "name":"Chalakudi",
        "code":"CKI"
    },
    {
        "name":"Changanacherry",
        "code":"CGY"
    },
    {
        "name":"Charvattur",
        "code":"CHV"
    },
    {
        "name":"Chengannur",
        "code":"CNGR"
    },
    {
        "name":"Chirayinkil",
        "code":"CRY"
    },
    {
        "name":"Dhanuvachapuram",
        "code":"DAVM"
    },
    {
        "name":"Divinenagar",
        "code":"DINR"
    },
    {
        "name":"Edappally",
        "code":"IPL"
    },
    {
        "name":"Ernakulam Junction",
        "code":"ERS"
    },
    {
        "name":"Ernakulam Town",
        "code":"ERN"
    },
    {
        "name":"Ettumanur",
        "code":"ETM"
    },
    {
        "name":"Ezhimala",
        "code":"ELM"
    },
    {
        "name":"Ferok",
        "code":"FK"
    },
    {
        "name":"Guruvayur",
        "code":"GUV"
    },
    {
        "name":"Haripad",
        "code":"HAD"
    },
    {
        "name":"Irinjalakuda",
        "code":"IJK"
    },
    {
        "name":"Kadakavur",
        "code":"KVU"
    },
    {
        "name":"Kadalundi",
        "code":"KN"
    },
    {
        "name":"Kanhangad",
        "code":"KZE"
    },
    {
        "name":"Kannapuram",
        "code":"KPQ"
    },
    {
        "name":"Karunagapalli",
        "code":"KPY"
    },
    {
        "name":"Kasaragod",
        "code":"KGQ"
    },
    {
        "name":"Kayamkulam",
        "code":"KYJ"
    },
    {
        "name":"Kazhakuttam",
        "code":"KZK"
    },
    {
        "name":"Kollam Junction",
        "code":"QLN"
    },
    {
        "name":"Kotikulam",
        "code":"KQK"
    },
    {
        "name":"Kottayam",
        "code":"KTYM"
    },
    {
        "name":"Koyilandy",
        "code":"QLD"
    },
    {
        "name":"Kumbala",
        "code":"KMQ"
    },
    {
        "name":"Kuttippuram",
        "code":"KTU"
    },
    {
        "name":"Manjeshwar",
        "code":"MJS"
    },
    {
        "name":"Mararikulam",
        "code":"MAKM"
    },
    {
        "name":"Mavelikara",
        "code":"MVLK"
    },
    {
        "name":"Mayyanad",
        "code":"MYY"
    },
    {
        "name":"Mulanturutti",
        "code":"MNTT"
    },
    {
        "name":"Munroturuttu",
        "code":"MQO"
    },
    {
        "name":"Murukkampuzha",
        "code":"MQU"
    },
    {
        "name":"Neyyattinkara",
        "code":"NYY"
    },
    {
        "name":"Nileshwar",
        "code":"NLE"
    },
    {
        "name":"Ottappalam",
        "code":"OTP"
    },
    {
        "name":"Palakkad Town",
        "code":"PGTN"
    },
    {
        "name":"Palghat",
        "code":"PGT"
    },
    {
        "name":"Parassala",
        "code":"PASA"
    },
    {
        "name":"Paravur",
        "code":"PVU"
    },
    {
        "name":"Parpanangadi",
        "code":"PGI"
    },
    {
        "name":"Pattambi",
        "code":"PTB"
    },
    {
        "name":"Payangadi",
        "code":"PAZ"
    },
    {
        "name":"Payyanur",
        "code":"PAY"
    },
    {
        "name":"Payyoli",
        "code":"PYOL"
    },
    {
        "name":"Piravam Road",
        "code":"PVRD"
    },
    {
        "name":"Pudukad",
        "code":"PUK"
    },
    {
        "name":"Punkunnam",
        "code":"PNQ"
    },
    {
        "name":"Sasthamkotta",
        "code":"STKT"
    },
    {
        "name":"Shertalai",
        "code":"SRTL"
    },
    {
        "name":"Shoranur",
        "code":"SRR"
    },
    {
        "name":"Tanur",
        "code":"TA"
    },
    {
        "name":"Tellicherry",
        "code":"TLY"
    },
    {
        "name":"Thiruvananthapuram Pettah",
        "code":"TVP"
    },
    {
        "name":"Tirunnavaya",
        "code":"TUA"
    },
    {
        "name":"Tirur",
        "code":"TIR"
    },
    {
        "name":"Tiruvalla",
        "code":"TRVL"
    },
    {
        "name":"Trichur",
        "code":"TCR"
    },
    {
        "name":"Trikarpur",
        "code":"TKQ"
    },
    {
        "name":"Tripunittura",
        "code":"TRTR"
    },
    {
        "name":"Trivandrum Central",
        "code":"TVC"
    },
    {
        "name":"Trivandrum Kochuveli",
        "code":"KCVL"
    },
    {
        "name":"Turavur",
        "code":"TUVR"
    },
    {
        "name":"Uppala",
        "code":"UAA"
    },
    {
        "name":"Vaikam Road",
        "code":"VARD"
    },
    {
        "name":"Valapattanam",
        "code":"VAPM"
    },
    {
        "name":"Vallikunnu",
        "code":"VLI"
    },
    {
        "name":"Varkala Sivagiri Station",
        "code":"VAK"
    },
    {
        "name":"Wadakanchery",
        "code":"WKI"
    },
    {
        "name":"Adarsh Nagar",
        "code":"ANDI"
    },
    {
        "name":"Anand Vihar",
        "code":"ANVR"
    },
    {
        "name":"Anand Vihar Terminus",
        "code":"ANVT"
    },
    {
        "name":"Badli",
        "code":"BHD"
    },
    {
        "name":"Bijwasan",
        "code":"BWSN"
    },
    {
        "name":"Delhi",
        "code":"DLI"
    },
    {
        "name":"Delhi Cantonment",
        "code":"DEC"
    },
    {
        "name":"Delhi Kishanganj",
        "code":"DKZ"
    },
    {
        "name":"Delhi Safdarjung",
        "code":"DSJ"
    },
    {
        "name":"Delhi Sarai Rohilla",
        "code":"DEE"
    },
    {
        "name":"Delhi Shahdara",
        "code":"DSA"
    },
    {
        "name":"Hazrat Nizamuddin",
        "code":"NZM"
    },
    {
        "name":"Mangolpuri",
        "code":"MGLP"
    },
    {
        "name":"Nangloi",
        "code":"NNO"
    },
    {
        "name":"Narela",
        "code":"NUR"
    },
    {
        "name":"New Delhi",
        "code":"NDLS"
    },
    {
        "name":"Okhla",
        "code":"OKA"
    },
    {
        "name":"Palam",
        "code":"PM"
    },
    {
        "name":"Shakurbasti",
        "code":"SSB"
    },
    {
        "name":"Shivaji Bridge",
        "code":"CSB"
    },
    {
        "name":"Subzi Mandi",
        "code":"SZM"
    },
    {
        "name":"Tilak Bridge",
        "code":"TKJ"
    },
    {
        "name":"Tuglakabad",
        "code":"TKD"
    },
    {
        "name":"Viveka Vihar",
        "code":"VVB"
    },
    {
        "name":"Aattur",
        "code":"ATU"
    },
    {
        "name":"Aduturai",
        "code":"ADT"
    },
    {
        "name":"Ambaturai",
        "code":"ABI"
    },
    {
        "name":"Ambur",
        "code":"AB"
    },
    {
        "name":"Anavardikhanpet",
        "code":"AVN"
    },
    {
        "name":"Arakkonam Junction",
        "code":"AJJ"
    },
    {
        "name":"Aralvaymozhi",
        "code":"AAY"
    },
    {
        "name":"Ariyalur",
        "code":"ALU"
    },
    {
        "name":"Arumuganeri",
        "code":"ANY"
    },
    {
        "name":"Avadi",
        "code":"AVD"
    },
    {
        "name":"Ayodhyapattanam",
        "code":"APN"
    },
    {
        "name":"Bommidi",
        "code":"BQI"
    },
    {
        "name":"Budalur",
        "code":"BAL"
    },
    {
        "name":"Buddireddippati",
        "code":"BDY"
    },
    {
        "name":"Chengalpattu",
        "code":"CGL"
    },
    {
        "name":"Chennai Central",
        "code":"MAS"
    },
    {
        "name":"Chennai Egmore",
        "code":"MS"
    },
    {
        "name":"Chettinad",
        "code":"CTND"
    },
    {
        "name":"Chidambaram",
        "code":"CDM"
    },
    {
        "name":"Chinna Salem",
        "code":"CHSM"
    },
    {
        "name":"Coimbatore Junction",
        "code":"CBE"
    },
    {
        "name":"Coimbatore North Junction",
        "code":"CBF"
    },
    {
        "name":"Cuddalore Port",
        "code":"CUPJ"
    },
    {
        "name":"Devakottai Road",
        "code":"DKO"
    },
    {
        "name":"",
        "code":"DPJ"
    }
];

exports.getStationCode=function(stationName){
    var stationID=-1;
    stations.forEach(function(value){
        if(value['name'].toUpperCase()==stationName.toUpperCase())
        {
            stationID=value['code'];
        }
    });
    return stationID;
};
