/**
 * Created by Snippy Valson on 21/7/16.
 */
var stations=[
    {
        "name":"Alappuzha",
        "code":"ALLP"
    },
    {
        "name":"Aluva",
        "code":"AWY"
    },
    {
        "name":"Angamaly",
        "code":"AFK"
    },
    {
        "name":"Badagara",
        "code":"BDJ"
    },
    {
        "name":"Bekal Fort",
        "code":"BFR"
    },
    {
        "name":"Calicut",
        "code":"CLT"
    },
    {
        "name":"Cannanore",
        "code":"CAN"
    },
    {
        "name":"Chalakudi",
        "code":"CKI"
    },
    {
        "name":"Changanacherry",
        "code":"CGY"
    },
    {
        "name":"Charvattur",
        "code":"CHV"
    },
    {
        "name":"Chengannur",
        "code":"CNGR"
    },
    {
        "name":"Chirayinkil",
        "code":"CRY"
    },
    {
        "name":"Dhanuvachapuram",
        "code":"DAVM"
    },
    {
        "name":"Divinenagar",
        "code":"DINR"
    },
    {
        "name":"Edappally",
        "code":"IPL"
    },
    {
        "name":"Ernakulam Junction",
        "code":"ERS"
    },
    {
        "name":"Ernakulam Town",
        "code":"ERN"
    },
    {
        "name":"Ettumanur",
        "code":"ETM"
    },
    {
        "name":"Ezhimala",
        "code":"ELM"
    },
    {
        "name":"Ferok",
        "code":"FK"
    },
    {
        "name":"Guruvayur",
        "code":"GUV"
    },
    {
        "name":"Haripad",
        "code":"HAD"
    },
    {
        "name":"Irinjalakuda",
        "code":"IJK"
    },
    {
        "name":"Kadakavur",
        "code":"KVU"
    },
    {
        "name":"Kadalundi",
        "code":"KN"
    },
    {
        "name":"Kanhangad",
        "code":"KZE"
    },
    {
        "name":"Kannapuram",
        "code":"KPQ"
    },
    {
        "name":"Karunagapalli",
        "code":"KPY"
    },
    {
        "name":"Kasaragod",
        "code":"KGQ"
    },
    {
        "name":"Kayamkulam",
        "code":"KYJ"
    },
    {
        "name":"Kazhakuttam",
        "code":"KZK"
    },
    {
        "name":"Kollam Junction",
        "code":"QLN"
    },
    {
        "name":"Kotikulam",
        "code":"KQK"
    },
    {
        "name":"Kottayam",
        "code":"KTYM"
    },
    {
        "name":"Koyilandy",
        "code":"QLD"
    },
    {
        "name":"Kumbala",
        "code":"KMQ"
    },
    {
        "name":"Kuttippuram",
        "code":"KTU"
    },
    {
        "name":"Manjeshwar",
        "code":"MJS"
    },
    {
        "name":"Mararikulam",
        "code":"MAKM"
    },
    {
        "name":"Mavelikara",
        "code":"MVLK"
    },
    {
        "name":"Mayyanad",
        "code":"MYY"
    },
    {
        "name":"Mulanturutti",
        "code":"MNTT"
    },
    {
        "name":"Munroturuttu",
        "code":"MQO"
    },
    {
        "name":"Murukkampuzha",
        "code":"MQU"
    },
    {
        "name":"Neyyattinkara",
        "code":"NYY"
    },
    {
        "name":"Nileshwar",
        "code":"NLE"
    },
    {
        "name":"Ottappalam",
        "code":"OTP"
    },
    {
        "name":"Palakkad Town",
        "code":"PGTN"
    },
    {
        "name":"Palghat",
        "code":"PGT"
    },
    {
        "name":"Parassala",
        "code":"PASA"
    },
    {
        "name":"Paravur",
        "code":"PVU"
    },
    {
        "name":"Parpanangadi",
        "code":"PGI"
    },
    {
        "name":"Pattambi",
        "code":"PTB"
    },
    {
        "name":"Payangadi",
        "code":"PAZ"
    },
    {
        "name":"Payyanur",
        "code":"PAY"
    },
    {
        "name":"Payyoli",
        "code":"PYOL"
    },
    {
        "name":"Piravam Road",
        "code":"PVRD"
    },
    {
        "name":"Pudukad",
        "code":"PUK"
    },
    {
        "name":"Punkunnam",
        "code":"PNQ"
    },
    {
        "name":"Sasthamkotta",
        "code":"STKT"
    },
    {
        "name":"Shertalai",
        "code":"SRTL"
    },
    {
        "name":"Shoranur",
        "code":"SRR"
    },
    {
        "name":"Tanur",
        "code":"TA"
    },
    {
        "name":"Tellicherry",
        "code":"TLY"
    },
    {
        "name":"Thiruvananthapuram Pettah",
        "code":"TVP"
    },
    {
        "name":"Tirunnavaya",
        "code":"TUA"
    },
    {
        "name":"Tirur",
        "code":"TIR"
    },
    {
        "name":"Tiruvalla",
        "code":"TRVL"
    },
    {
        "name":"Trichur",
        "code":"TCR"
    }












];